CREATE DATABASE MSN;
USE MSN;
SHOW DATABASES;
CREATE TABLE USER (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(20) PRIMARY KEY,
    password VARCHAR(20),
    identity VARCHAR(20)
);
DESCRIBE USER;

SELECT * FROM USER;
INSERT INTO USER (name, password, identity) VALUES ('admin', '123456', 'admin');
SELECT PASSWORD FROM USER WHERE name='admin';