"""empty message

Revision ID: 24363924a187
Revises: c9ea2ed87b7e
Create Date: 2025-07-17 01:09:53.142116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24363924a187'
down_revision = 'c9ea2ed87b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('pwd', sa.String(length=128), nullable=True),
    sa.Column('identity', sa.String(length=16), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
